<a href="https://colab.research.google.com/github/Kash6/MGAN/blob/main/cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

MessageError: ignored

In [ ]:
!unzip "/content/drive/MyDrive/B_40X.zip" -d "/content/c/"  

Archive:  /content/drive/MyDrive/B_40X.zip
   creating: /content/c/B_40X/
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-001.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-002.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-003.png  
 extracting: /content/c/B_40X/SOB_B_A-14-22549AB-40-004.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-005.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-006.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-007.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-008.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-009.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-010.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-011.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-012.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-013.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-014.png  
  inflating: /content/c/B_40X/SOB_B_A-14-22549AB-40-015.pn

In [ ]:
import glob
import numpy as np
from PIL import Image
filelist = glob.glob('/content/c/B_40X/*.png')
for fname in filelist:
  image=Image.open(fname)
  rimage=image.resize((64,64))
  rimage.save(fname)

x = np.array([np.array(Image.open(fname)) for fname in filelist])

In [ ]:
filelist = glob.glob('/content/c/B_40X/*.png')
for fname in filelist:
  image=Image.open(fname)
  print(image.size)

(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(64, 64)
(

In [ ]:
print(x)

[[[[239 158 225]
   [238 155 224]
   [243 159 225]
   ...
   [233 155 221]
   [247 193 237]
   [247 196 239]]

  [[233 157 222]
   [236 165 223]
   [230 143 213]
   ...
   [249 187 243]
   [243 185 236]
   [240 171 233]]

  [[247 177 234]
   [234 156 220]
   [231 143 216]
   ...
   [233 157 224]
   [233 161 228]
   [241 173 238]]

  ...

  [[249 159 207]
   [249 159 201]
   [244 156 188]
   ...
   [251 176 227]
   [254 166 226]
   [254 158 228]]

  [[251 176 213]
   [251 204 226]
   [250 232 227]
   ...
   [252 172 226]
   [253 162 218]
   [254 154 217]]

  [[252 183 215]
   [248 215 230]
   [250 213 227]
   ...
   [253 187 235]
   [252 184 228]
   [250 187 223]]]


 [[[188 181 188]
   [187 182 186]
   [186 180 185]
   ...
   [198 200 195]
   [198 201 194]
   [199 201 192]]

  [[187 179 187]
   [187 180 186]
   [185 178 184]
   ...
   [197 200 197]
   [196 201 195]
   [198 201 194]]

  [[186 178 187]
   [190 182 189]
   [189 181 188]
   ...
   [197 202 196]
   [197 201 195]
   [197 201

In [ ]:
x.shape

(370, 64, 64, 3)

In [ ]:
import pickle
filehandle=open("/content/l1.pkl",'wb')
pickle.dump(x, filehandle)

In [ ]:
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo)
    return dict
unpickle("/content/l1.pkl")    

array([[[[239, 158, 225],
         [238, 155, 224],
         [243, 159, 225],
         ...,
         [233, 155, 221],
         [247, 193, 237],
         [247, 196, 239]],

        [[233, 157, 222],
         [236, 165, 223],
         [230, 143, 213],
         ...,
         [249, 187, 243],
         [243, 185, 236],
         [240, 171, 233]],

        [[247, 177, 234],
         [234, 156, 220],
         [231, 143, 216],
         ...,
         [233, 157, 224],
         [233, 161, 228],
         [241, 173, 238]],

        ...,

        [[249, 159, 207],
         [249, 159, 201],
         [244, 156, 188],
         ...,
         [251, 176, 227],
         [254, 166, 226],
         [254, 158, 228]],

        [[251, 176, 213],
         [251, 204, 226],
         [250, 232, 227],
         ...,
         [252, 172, 226],
         [253, 162, 218],
         [254, 154, 217]],

        [[252, 183, 215],
         [248, 215, 230],
         [250, 213, 227],
         ...,
         [253, 187, 235],
        

In [ ]:
import os
filename="/content/L2.pkl"
if os.path.getsize(filename) > 0:      
    with open(filename, "rb") as file:
        unpickler = pickle.Unpickler(file)
        content = unpickler.load()